Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Billy/BITS/SoMeToolkit/__main__.py", line 7, in <module>
    controller.run()
  File "./src/controller.py", line 21, in run
    daemon.start()
  File "./src/daemon.py", line 132, in start
    self.run(*args, **kwargs)
  File "./src/controller.py", line 11, in run
    ThreadedCollector.go('follow')
  File "./src/twitter/ThreadedCollector.py", line 327, in go
    logDir = Config.get('files', 'log_dir', 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'files'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/twitter/ThreadedCollector.py", line 275, in _run
    self._read_loop(resp)
  File "/Users/Billy/BITS/SoMeToolkit/env/lib/python2.7/site-packages/tweepy/streaming.py", line 231, in _read_loop
    self._data(next_status_obj)
  File "/Users/Billy/BITS/SoMeToolkit/env/lib/python2.7/site-packages/tweepy/streaming.py", line 207, in _data
    if self.listener.on_data(data) is False:
  File "./src/twitter/ThreadedCollector.py", line 172, in on_data
    myFile = open(JSONfileName,'a')
IOError: [Errno 2] No such file or directory: '/Users/Billy/BITS/SoMeToolkit/src/twitter/raw_tweets//Users/Billy/BITS/SoMeToolkit/src/twitter20141111-1446-follow-/Users/Billy/BITS/SoMeToolkit/src/twittertweets_out.json'

